DROP TABLE IF EXISTS "game";
DROP TABLE IF EXISTS "board";

CREATE TABLE "game" (
	"id"	INTEGER,
	"sqltime"	TIMESTAMP NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
    "next_board_seqnr" INTEGER NOT NULL DEFAULT (0),
	 PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE "board" (
	"id"	INTEGER NOT NULL,
	"game_id"	INTEGER NOT NULL,
	"sqltime"	TIMESTAMP NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
	"seqnr"	 INTEGER NOT NULL,
	"turn"	INTEGER NOT NULL,
	"bar_r"	INTEGER NOT NULL,
	"bar_w"	INTEGER NOT NULL,
	"off_r"	INTEGER NOT NULL,
	"off_w"	INTEGER NOT NULL,
	"dice1"	INTEGER NOT NULL,
	"dice2"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("game_id") REFERENCES "game"("id")
);

CREATE TABLE "point" (
	"id"	INTEGER NOT NULL,
	"board_id"	INTEGER NOT NULL,
	"sqltime"	TIMESTAMP NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
	"idx"	INTEGER NOT NULL,
	"color"	INTEGER NOT NULL,
	"cnt"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("board_id") REFERENCES "board"("id")
);



